classDiagram
    Serializable <|.. Product
    SaleableItem <|.. Product
    Product <|-- Ticket
    Product <|-- Publication
    Publication <|-- Book
    Publication <|-- Magazine
    Magazine <|-- DiscMag
    Cart "0..*" --> "0..*" Product : contains

    class Cart{
        -Long id
        -List items
        +addItem(Product item)
        +getItems()
        +setItems(List items)
    }

    class Product{
        -Long id
        -String productId
    }

    class Serializable{
        <<interface>>
    }
    class SaleableItem {
        <<interface>>
        +sellItem()
        +getPrice()

    }
    class Ticket{
        +description
        +price
        +sellItem()
    }
    class Publication{
        <<Abstract>>
        -String title
        -double price
        -int copies
        +getPrice()

        +Publication()
        +Publication(String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()

    }
    class Book{
        -String isbn
        -String author
        +sellItem()

        +Book()
        +Book(String author)
        +Book(String author, String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()

    }
    class Magazine{
        -int orderQty
        -java.util.Date currentIssue

        +Magazine()
        +Magazine(int orderQty, Date currentIssue, String title, double price, int copies)

        +sellItem()
    }
    class DiscMag{
        -boolean hasDisc
        +sellItem()

        +DiscMag()
        +DiscMag(boolean, hasDisc, int orderQty, Date currentIssue, String title, double price, int copies)

    }
